version: "3"

services: 
  db:
    image: postgres:12-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:  
      - /psql12:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: "samit@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports: 
      - "8800:80"
